version: "3"
services:
    app:
      build: .
      # container_name: nodeapp
      volumes:
        - ./src:/app/src
      # ports:
      #   - "3000:3000"
      depends_on:
        - postgres
        - redis
        # - mongo
        # - mongo-express
        
    # mongo:
    #   image: mongo
    #   container_name: mongo
    #   restart: always
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: example
    # mongo-express:
    #   image: mongo-express
    #   container_name: mongo-express
    #   depends_on:
    #     - mongo
    #   restart: always
    #   ports:
    #     - 8081:8081
    #   environment:
    #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    postgres:  
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgresuser
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=test
      ports:
        - '5432:5432'

    redis:
      image: redis
    nginx:
      image: nginx
      ports:
        - "8090:80"
      volumes:
        - ./conf.d:/etc/nginx/conf.d
      depends_on:
        - app
        - postgres
        - redis